name: frhoegnjtg
favicon: null
layout_spectrum: 0.965209593065083
typography_spectrum: 0.5877085162792355
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.6321177964564413
  lightness: 0.115723033901304
  saturation: 0.6534002674743533
  rhythmicContrast: 0.7726586384233087
purpose: []
